import React from 'react'
import './Upload.css'

function Upload() {
  return (
    <section className='sample'>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    BUKAS NA ULIT AYAKO NA HAHAHAHAHAH<br/>
    </section>
  )
}

export default Upload;